src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publishedAt = null;

   

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    
    #[ORM\Column]
    private ?int $numLikes = null;

    #[ORM\Column]
    private ?int $numComments = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'posts', targetEntity: User::class)]
    private $User;

    public function __construct()
    {
    $this->publishedAt = new \DateTime();
    $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getUser(): ?User
    { 
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getNumLikes(): ?int
    {
        return $this->numLikes;
    }

    public function setNumLikes(int $numLikes): self
    {
        $this->numLikes = $numLikes;

        return $this;
    }

    public function getNumComments(): ?int
    {
        return $this->numComments;
    }

    public function setNumComments(int $numComments): self
    {
        $this->numComments = $numComments;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    
}

src/Controller/BlogController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Post;
use App\Form\PostFormType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class BlogController extends AbstractController
{


    /**
     * @Route("/blog", name="blog")
     */
    public function blog(): Response
    {
        return $this->render('blog/blog.html.twig', []);
    }
    /**
     * @Route("/single", name="single")
     */
    public function single(): Response
    {
        return $this->render('blog/single_post.html.twig', []);
    }

    /**
     * @Route("/blog/new", name="new_post")
     */
    public function newPost(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger): Response
    {
        $post = new Post();
        $form = $this->createForm(PostFormType::class, $post);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('Image')->getData();
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();
        
                // Move the file to the directory where images are stored
                try {
                    
                    $file->move(
                        $this->getParameter('images_directory'), $newFilename
                    );
                   
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $post->setImage($newFilename);
            }
        
            $post = $form->getData();   
            $post->setSlug($slugger->slug($post->getTitle()));
           
            $post->setUser($this->getUser());
            $post->setNumLikes(0);
            $post->setNumComments(0);
            $entityManager = $doctrine->getManager();    
            $entityManager->persist($post);
            $entityManager->flush();
            return $this->redirectToRoute('single_post', ["slug" => $post->getSlug()]);
        }
        return $this->render('blog/new_post.html.twig', array(
            'form' => $form->createView()    
        ));
    }
    
    #[Route('/single_post/{slug}', name: 'single_post')]
    public function post(ManagerRegistry $doctrine, $slug): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $post = $repository->findOneBy(["slug"=>$slug]);
        $recents = $repository->findRecents();
        return $this->render('blog/single_post.html.twig', [
            'post' => $post,
            'recents' => $recents
        ]);
    }


    #[Route('/blog/{page}', name: 'blog')]
    public function index(ManagerRegistry $doctrine, int $page = 1): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $posts = $repository->findAllPaginated($page);
    
        return $this->render('blog/blog.html.twig', [
            'posts' => $posts,
        ]);
    }
    

    #[Route('/single_post/{slug}/like', name: 'post_like')]
    public function like(ManagerRegistry $doctrine, $slug): Response
    {
        $repository = $doctrine->getRepository(Post::class);
        $post = $repository->findOneBy(["slug"=>$slug]);
        if ($post){
            $post->setNumLikes($post->getNumLikes() + 1);
            $entityManager = $doctrine->getManager();    
            $entityManager->persist($post);
            $entityManager->flush();
        }
        return $this->redirectToRoute('single_post', ["slug" => $post->getSlug()]);
    
    }
    
}

templates/blog/new_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}New Post{% endblock %}
{%block body_id %}principal{% endblock %}

{% block body%}
<br>
<br>
<br>
<br>
<br>
<!-- Principal Content Start -->
   <div id="new Post">
   	  <div class="container">
   	    <div class="col-xs-12 col-sm-8 col-sm-push-2">
       	   <h1>New Post</h1>
			   {{ form(form, {'attr': {'class':'form-horizontal'}}) }}
       	   <hr class="divider">
		</div>   
   	  </div>
   </div>
<!-- Principal Content Start -->
{% endblock %}

templates/blog/single_post.html.twig
{% extends 'base.html.twig' %}
{% block title%}Post{% endblock %}
{% block body%}
<!-- Principal Content Start -->
   <div id="single">
     <div class="container">
      {% if not post %}
      <h2>Post not found</h2>
      {% else %}
    <!-- Full Article -->
      <div class="row">
      <div class="post-heading">
        <img class="img-responsive" src="{{ asset('images/blog/' ~ post.image) }}" alt="{{post.title}}">
      </div>
      <h2>{{post.title}}</h2>
      <hr class="subtitle">
      <div class=" block1">
      <div class="col-xs-12 col-sm-9">
       <p>
       {{post.content}}
       </p>
        <h4>- By {{ post.user.name}}</h4>
        <hr>
        <ul class="list-inline">
          <li>{{ post.publishedAt | date('d') }} {{ post.publishedAt | date('F') }}</li>
          <li><a class="page-scroll" href="#form">COMMENT</a> |</li>
          <li><a href="{{ path('post_like', {slug: post.slug}) }}">LIKE</a> <i class="fa fa-heart sr-icons"></i> {{post.numLikes}}</li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-3">
        <h4>Recent Post</h4>
        <hr class="subtitle1">
        {% for recent in recents %}
        {{ include ('partials/recent_post.html.twig', {'recent': recent}) }}
        {% endfor %}
      </div>
      </div>
      </div>
    <!-- End of Full Article -->

    <!-- Comments -->
      <div class="row">
      <div class="col-xs-12 col-sm-12 block2">
        {% for comment in post.comments %}
        {{ include ('partials/comment.html.twig', {'comment': comment}) }}
        {% endfor %}
          <hr class="line">
            {{ include ('partials/form_comment.html.twig') }}
          </div>
      </div>
      </div>
    <!-- End of Comments -->  
     </div>
      {% endif %}

   </div>
<!-- End of Principal Content Start -->
{% endblock %}